### ISSUE TITLE
No build on Ubuntu-17.04 with amdgpu-pro-17.10

### ISSUE THREAD

**Issue by EUViking** [fireice-uk/xmr-stak-amd#32]
After testing Master-branch on Ubuntu-17.04 with amdgpu-pro-16.60, where the Miner crashed after about a minute, I upgraded my installation to amdgpu-pro-17.10 and Dev-branch, but then it does not even build:
```
Miner-01:~/Miners/xmr-stak-amd/git/xmr-stak-amd$ git checkout origin/dev;
M	config.txt
HEAD is now at 4a8f0e3... Merge pull request #28 from psychocrypt/topic-versionFile
sysadm@gpu-miner-01:~/Miners/xmr-stak-amd/git/xmr-stak-amd$ cmake .
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sysadm/Miners/xmr-stak-amd/git/xmr-stak-amd
Miner-01:~/Miners/xmr-stak-amd/git/xmr-stak-amd$ make clean
Miner-01:~/Miners/xmr-stak-amd/git/xmr-stak-amd$ make 
[  5%] Building C object CMakeFiles/xmr-stak-c.dir/crypto/c_blake256.c.o
[ 10%] Building C object CMakeFiles/xmr-stak-c.dir/crypto/c_groestl.c.o
[ 15%] Building C object CMakeFiles/xmr-stak-c.dir/crypto/c_jh.c.o
[ 21%] Building C object CMakeFiles/xmr-stak-c.dir/crypto/c_keccak.c.o
[ 26%] Building C object CMakeFiles/xmr-stak-c.dir/crypto/c_skein.c.o
[ 31%] Building C object CMakeFiles/xmr-stak-c.dir/crypto/soft_aes.c.o
[ 36%] Building C object CMakeFiles/xmr-stak-c.dir/amd_gpu/gpu.c.o
/home/sysadm/Miners/xmr-stak-amd/git/xmr-stak-amd/amd_gpu/gpu.c: In function ‘XMRRunJob’:
/home/sysadm/Miners/xmr-stak-amd/git/xmr-stak-amd/amd_gpu/gpu.c:680:31: warning: implicit declaration of function ‘ceil’ [-Wimplicit-function-declaration]
    BranchNonces[i] = ((size_t)ceil( (double)BranchNonces[i] / (double)w_size) ) * w_size;
                               ^~~~
/home/sysadm/Miners/xmr-stak-amd/git/xmr-stak-amd/amd_gpu/gpu.c:680:31: warning: incompatible implicit declaration of built-in function ‘ceil’
/home/sysadm/Miners/xmr-stak-amd/git/xmr-stak-amd/amd_gpu/gpu.c:680:31: note: include ‘<math.h>’ or provide a declaration of ‘ceil’
[ 42%] Linking C static library libxmr-stak-c.a
[ 42%] Built target xmr-stak-c
[ 47%] Building CXX object CMakeFiles/xmr-stak-amd.dir/cli-miner.cpp.o
[ 52%] Building CXX object CMakeFiles/xmr-stak-amd.dir/console.cpp.o
[ 57%] Building CXX object CMakeFiles/xmr-stak-amd.dir/executor.cpp.o
[ 63%] Building CXX object CMakeFiles/xmr-stak-amd.dir/httpd.cpp.o
[ 68%] Building CXX object CMakeFiles/xmr-stak-amd.dir/jconf.cpp.o
[ 73%] Building CXX object CMakeFiles/xmr-stak-amd.dir/jpsock.cpp.o
[ 78%] Building CXX object CMakeFiles/xmr-stak-amd.dir/minethd.cpp.o
[ 84%] Building CXX object CMakeFiles/xmr-stak-amd.dir/socket.cpp.o
[ 89%] Building CXX object CMakeFiles/xmr-stak-amd.dir/webdesign.cpp.o
[ 94%] Building CXX object CMakeFiles/xmr-stak-amd.dir/crypto/cryptonight_common.cpp.o
[100%] Linking CXX executable bin/xmr-stak-amd
libxmr-stak-c.a(gpu.c.o): In function `InitOpenCLGpu':
gpu.c:(.text+0x4f4): undefined reference to `clGetDeviceInfo'
gpu.c:(.text+0x56a): undefined reference to `clCreateCommandQueueWithProperties'
gpu.c:(.text+0x5d3): undefined reference to `clCreateBuffer'
gpu.c:(.text+0xa09): undefined reference to `clCreateBuffer'
gpu.c:(.text+0xa5b): undefined reference to `clCreateBuffer'
gpu.c:(.text+0xaa4): undefined reference to `clCreateBuffer'
gpu.c:(.text+0xae5): undefined reference to `clCreateBuffer'
libxmr-stak-c.a(gpu.c.o):gpu.c:(.text+0xb2b): more undefined references to `clCreateBuffer' follow
libxmr-stak-c.a(gpu.c.o): In function `InitOpenCLGpu':
gpu.c:(.text+0xbf2): undefined reference to `clCreateProgramWithSource'
gpu.c:(.text+0xc6a): undefined reference to `clBuildProgram'
gpu.c:(.text+0xc93): undefined reference to `clGetProgramBuildInfo'
gpu.c:(.text+0xd21): undefined reference to `clCreateKernel'
gpu.c:(.text+0xd82): undefined reference to `clGetProgramBuildInfo'
gpu.c:(.text+0xdf6): undefined reference to `clGetProgramBuildInfo'
libxmr-stak-c.a(gpu.c.o): In function `InitOpenCL':
gpu.c:(.text+0xea5): undefined reference to `clGetPlatformIDs'
gpu.c:(.text+0xedb): undefined reference to `clGetPlatformIDs'
gpu.c:(.text+0xf75): undefined reference to `clGetDeviceIDs'
gpu.c:(.text+0xff6): undefined reference to `clGetDeviceIDs'
gpu.c:(.text+0x10c1): undefined reference to `clCreateContext'
gpu.c:(.text+0x1182): undefined reference to `clGetDeviceIDs'
libxmr-stak-c.a(gpu.c.o): In function `XMRSetJob':
gpu.c:(.text+0x1243): undefined reference to `clEnqueueWriteBuffer'
gpu.c:(.text+0x12b0): undefined reference to `clSetKernelArg'
gpu.c:(.text+0x15d6): undefined reference to `clSetKernelArg'
gpu.c:(.text+0x162e): undefined reference to `clSetKernelArg'
gpu.c:(.text+0x1675): undefined reference to `clSetKernelArg'
gpu.c:(.text+0x16b1): undefined reference to `clSetKernelArg'
libxmr-stak-c.a(gpu.c.o):gpu.c:(.text+0x16ed): more undefined references to `clSetKernelArg' follow
libxmr-stak-c.a(gpu.c.o): In function `XMRRunJob':
gpu.c:(.text+0x19e5): undefined reference to `clEnqueueWriteBuffer'
gpu.c:(.text+0x1a33): undefined reference to `clEnqueueWriteBuffer'
gpu.c:(.text+0x1a9c): undefined reference to `clFinish'
gpu.c:(.text+0x1afc): undefined reference to `clEnqueueNDRangeKernel'
gpu.c:(.text+0x1b64): undefined reference to `clEnqueueNDRangeKernel'
gpu.c:(.text+0x1bc9): undefined reference to `clEnqueueNDRangeKernel'
gpu.c:(.text+0x1c16): undefined reference to `clEnqueueReadBuffer'
gpu.c:(.text+0x1c52): undefined reference to `clEnqueueReadBuffer'
gpu.c:(.text+0x1c8e): undefined reference to `clEnqueueReadBuffer'
gpu.c:(.text+0x1cca): undefined reference to `clEnqueueReadBuffer'
gpu.c:(.text+0x1ce2): undefined reference to `clFinish'
gpu.c:(.text+0x1d1c): undefined reference to `clSetKernelArg'
gpu.c:(.text+0x1daa): undefined reference to `clEnqueueNDRangeKernel'
gpu.c:(.text+0x1df0): undefined reference to `clEnqueueReadBuffer'
gpu.c:(.text+0x1e05): undefined reference to `clFinish'
collect2: error: ld returned 1 exit status
CMakeFiles/xmr-stak-amd.dir/build.make:333: recipe for target 'bin/xmr-stak-amd' failed
make[2]: *** [bin/xmr-stak-amd] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/xmr-stak-amd.dir/all' failed
make[1]: *** [CMakeFiles/xmr-stak-amd.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```
CLinfo:
```
Number of platforms:				 1
  Platform Profile:				 FULL_PROFILE
  Platform Version:				 OpenCL 2.0 AMD-APP (2348.3)
  Platform Name:				 AMD Accelerated Parallel Processing
  Platform Vendor:				 Advanced Micro Devices, Inc.
  Platform Extensions:				 cl_khr_icd cl_amd_event_callback cl_amd_offline_devices 


  Platform Name:				 AMD Accelerated Parallel Processing
Number of devices:				 2
  Device Type:					 CL_DEVICE_TYPE_GPU
  Vendor ID:					 1002h
  Board name:					 AMD Radeon (TM) RX 480 Graphics
  Device Topology:				 PCI[ B#1, D#0, F#0 ]
  Max compute units:				 36
  Max work items dimensions:			 3
    Max work items[0]:				 256
    Max work items[1]:				 256
    Max work items[2]:				 256
  Max work group size:				 256
  Preferred vector width char:			 4
  Preferred vector width short:			 2
  Preferred vector width int:			 1
  Preferred vector width long:			 1
  Preferred vector width float:			 1
  Preferred vector width double:		 1
  Native vector width char:			 4
  Native vector width short:			 2
  Native vector width int:			 1
  Native vector width long:			 1
  Native vector width float:			 1
  Native vector width double:			 1
  Max clock frequency:				 1342Mhz
  Address bits:					 64
  Max memory allocation:			 4244635648
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 8
  Max image 2D width:				 16384
  Max image 2D height:				 16384
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 16
  Max size of kernel argument:			 1024
  Alignment (bits) of base address:		 2048
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 No
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 16384
  Global memory size:				 8566132736
  Constant buffer size:				 4244635648
  Max number of constant args:			 8
  Local memory type:				 Scratchpad
  Local memory size:				 32768
  Max pipe arguments:				 0
  Max pipe active reservations:			 0
  Max pipe packet size:				 0
  Max global variable size:			 0
  Max global variable preferred total size:	 0
  Max read/write image args:			 0
  Max on device events:				 0
  Queue on device max size:			 0
  Max on device queues:				 0
  Queue on device preferred size:		 0
  SVM capabilities:				 
    Coarse grain buffer:			 No
    Fine grain buffer:				 No
    Fine grain system:				 No
    Atomics:					 No
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 64
  Error correction support:			 0
  Unified memory for Host and Device:		 0
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 No
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 No
    Profiling :					 No
  Platform ID:					 0x7f08821f0e98
  Name:						 Ellesmere
  Vendor:					 Advanced Micro Devices, Inc.
  Device OpenCL C version:			 OpenCL C 1.2 
  Driver version:				 2348.3
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 AMD-APP (2348.3)
  Extensions:					 cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_fp16 cl_khr_gl_sharing cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_image2d_from_buffer cl_khr_spir cl_khr_gl_event 


  Device Type:					 CL_DEVICE_TYPE_CPU
  Vendor ID:					 1002h
  Board name:					 
  Max compute units:				 2
  Max work items dimensions:			 3
    Max work items[0]:				 1024
    Max work items[1]:				 1024
    Max work items[2]:				 1024
  Max work group size:				 1024
  Preferred vector width char:			 16
  Preferred vector width short:			 8
  Preferred vector width int:			 4
  Preferred vector width long:			 2
  Preferred vector width float:			 4
  Preferred vector width double:		 2
  Native vector width char:			 16
  Native vector width short:			 8
  Native vector width int:			 4
  Native vector width long:			 2
  Native vector width float:			 4
  Native vector width double:			 2
  Max clock frequency:				 3000Mhz
  Address bits:					 64
  Max memory allocation:			 2147483648
  Image support:				 Yes
  Max number of images read arguments:		 128
  Max number of images write arguments:		 64
  Max image 2D width:				 8192
  Max image 2D height:				 8192
  Max image 3D width:				 2048
  Max image 3D height:				 2048
  Max image 3D depth:				 2048
  Max samplers within kernel:			 16
  Max size of kernel argument:			 4096
  Alignment (bits) of base address:		 1024
  Minimum alignment (bytes) for any datatype:	 128
  Single precision floating point capability
    Denorms:					 Yes
    Quiet NaNs:					 Yes
    Round to nearest even:			 Yes
    Round to zero:				 Yes
    Round to +ve and infinity:			 Yes
    IEEE754-2008 fused multiply-add:		 Yes
  Cache type:					 Read/Write
  Cache line size:				 64
  Cache size:					 16384
  Global memory size:				 8369180672
  Constant buffer size:				 65536
  Max number of constant args:			 8
  Local memory type:				 Global
  Local memory size:				 32768
  Max pipe arguments:				 16
  Max pipe active reservations:			 16
  Max pipe packet size:				 2147483648
  Max global variable size:			 1879048192
  Max global variable preferred total size:	 1879048192
  Max read/write image args:			 64
  Max on device events:				 0
  Queue on device max size:			 0
  Max on device queues:				 0
  Queue on device preferred size:		 0
  SVM capabilities:				 
    Coarse grain buffer:			 No
    Fine grain buffer:				 No
    Fine grain system:				 No
    Atomics:					 No
  Preferred platform atomic alignment:		 0
  Preferred global atomic alignment:		 0
  Preferred local atomic alignment:		 0
  Kernel Preferred work group size multiple:	 1
  Error correction support:			 0
  Unified memory for Host and Device:		 1
  Profiling timer resolution:			 1
  Device endianess:				 Little
  Available:					 Yes
  Compiler available:				 Yes
  Execution capabilities:				 
    Execute OpenCL kernels:			 Yes
    Execute native function:			 Yes
  Queue on Host properties:				 
    Out-of-Order:				 No
    Profiling :					 Yes
  Queue on Device properties:				 
    Out-of-Order:				 No
    Profiling :					 No
  Platform ID:					 0x7f08821f0e98
  Name:						 Intel(R) Pentium(R) D CPU 3.00GHz
  Vendor:					 GenuineIntel
  Device OpenCL C version:			 OpenCL C 1.2 
  Driver version:				 2348.3 (sse2)
  Profile:					 FULL_PROFILE
  Version:					 OpenCL 1.2 AMD-APP (2348.3)
  Extensions:					 cl_khr_fp64 cl_amd_fp64 cl_khr_global_int32_base_atomics cl_khr_global_int32_extended_atomics cl_khr_local_int32_base_atomics cl_khr_local_int32_extended_atomics cl_khr_int64_base_atomics cl_khr_int64_extended_atomics cl_khr_3d_image_writes cl_khr_byte_addressable_store cl_khr_gl_sharing cl_ext_device_fission cl_amd_device_attribute_query cl_amd_vec3 cl_amd_printf cl_amd_media_ops cl_amd_media_ops2 cl_amd_popcnt cl_khr_spir cl_khr_gl_event 
```
Any suggestions?

**Comment by psychocrypt** [comment]
One issue with the dev is a missing `#include <math.h>`. I will fix it soon.

Please remove all old temporary files before compiling ( you cmake cache is dirty from the old installation)
Call the following command.
```
cd ~/Miners/xmr-stak-amd/git/xmr-stak-amd
rm -r CMake*
cmake .
make -j
make install
```

**Comment by EUViking** [comment]
> rm -r CMake*

makes the cmake not runnable, but re-cloning the git, switching to Dev and adding the patch, still ends in error at make:
```
Miner-01:~/Miners/xmr-stak-amd/git/xmr-stak-amd$ make 
[  5%] Building C object CMakeFiles/xmr-stak-c.dir/crypto/c_blake256.c.o
[ 10%] Building C object CMakeFiles/xmr-stak-c.dir/crypto/c_groestl.c.o
[ 15%] Building C object CMakeFiles/xmr-stak-c.dir/crypto/c_jh.c.o
[ 21%] Building C object CMakeFiles/xmr-stak-c.dir/crypto/c_keccak.c.o
[ 26%] Building C object CMakeFiles/xmr-stak-c.dir/crypto/c_skein.c.o
[ 31%] Building C object CMakeFiles/xmr-stak-c.dir/crypto/soft_aes.c.o
[ 36%] Building C object CMakeFiles/xmr-stak-c.dir/amd_gpu/gpu.c.o
[ 42%] Linking C static library libxmr-stak-c.a
[ 42%] Built target xmr-stak-c
[ 47%] Building CXX object CMakeFiles/xmr-stak-amd.dir/cli-miner.cpp.o
[ 52%] Building CXX object CMakeFiles/xmr-stak-amd.dir/console.cpp.o
[ 57%] Building CXX object CMakeFiles/xmr-stak-amd.dir/executor.cpp.o
[ 63%] Building CXX object CMakeFiles/xmr-stak-amd.dir/httpd.cpp.o
[ 68%] Building CXX object CMakeFiles/xmr-stak-amd.dir/jconf.cpp.o
[ 73%] Building CXX object CMakeFiles/xmr-stak-amd.dir/jpsock.cpp.o
[ 78%] Building CXX object CMakeFiles/xmr-stak-amd.dir/minethd.cpp.o
[ 84%] Building CXX object CMakeFiles/xmr-stak-amd.dir/socket.cpp.o
[ 89%] Building CXX object CMakeFiles/xmr-stak-amd.dir/webdesign.cpp.o
[ 94%] Building CXX object CMakeFiles/xmr-stak-amd.dir/crypto/cryptonight_common.cpp.o
[100%] Linking CXX executable bin/xmr-stak-amd
libxmr-stak-c.a(gpu.c.o): In function `InitOpenCLGpu':
gpu.c:(.text+0x4f4): undefined reference to `clGetDeviceInfo'
gpu.c:(.text+0x56a): undefined reference to `clCreateCommandQueueWithProperties'
gpu.c:(.text+0x5d3): undefined reference to `clCreateBuffer'
gpu.c:(.text+0xa09): undefined reference to `clCreateBuffer'
gpu.c:(.text+0xa5b): undefined reference to `clCreateBuffer'
gpu.c:(.text+0xaa4): undefined reference to `clCreateBuffer'
gpu.c:(.text+0xae5): undefined reference to `clCreateBuffer'
libxmr-stak-c.a(gpu.c.o):gpu.c:(.text+0xb2b): more undefined references to `clCreateBuffer' follow
libxmr-stak-c.a(gpu.c.o): In function `InitOpenCLGpu':
gpu.c:(.text+0xbf2): undefined reference to `clCreateProgramWithSource'
gpu.c:(.text+0xc6a): undefined reference to `clBuildProgram'
gpu.c:(.text+0xc93): undefined reference to `clGetProgramBuildInfo'
gpu.c:(.text+0xd21): undefined reference to `clCreateKernel'
gpu.c:(.text+0xd82): undefined reference to `clGetProgramBuildInfo'
gpu.c:(.text+0xdf6): undefined reference to `clGetProgramBuildInfo'
libxmr-stak-c.a(gpu.c.o): In function `InitOpenCL':
gpu.c:(.text+0xea5): undefined reference to `clGetPlatformIDs'
gpu.c:(.text+0xedb): undefined reference to `clGetPlatformIDs'
gpu.c:(.text+0xf75): undefined reference to `clGetDeviceIDs'
gpu.c:(.text+0xff6): undefined reference to `clGetDeviceIDs'
gpu.c:(.text+0x10c1): undefined reference to `clCreateContext'
gpu.c:(.text+0x1182): undefined reference to `clGetDeviceIDs'
libxmr-stak-c.a(gpu.c.o): In function `XMRSetJob':
gpu.c:(.text+0x1243): undefined reference to `clEnqueueWriteBuffer'
gpu.c:(.text+0x12b0): undefined reference to `clSetKernelArg'
gpu.c:(.text+0x15d6): undefined reference to `clSetKernelArg'
gpu.c:(.text+0x162e): undefined reference to `clSetKernelArg'
gpu.c:(.text+0x1675): undefined reference to `clSetKernelArg'
gpu.c:(.text+0x16b1): undefined reference to `clSetKernelArg'
libxmr-stak-c.a(gpu.c.o):gpu.c:(.text+0x16ed): more undefined references to `clSetKernelArg' follow
libxmr-stak-c.a(gpu.c.o): In function `XMRRunJob':
gpu.c:(.text+0x19e5): undefined reference to `clEnqueueWriteBuffer'
gpu.c:(.text+0x1a33): undefined reference to `clEnqueueWriteBuffer'
gpu.c:(.text+0x1a9c): undefined reference to `clFinish'
gpu.c:(.text+0x1afc): undefined reference to `clEnqueueNDRangeKernel'
gpu.c:(.text+0x1b64): undefined reference to `clEnqueueNDRangeKernel'
gpu.c:(.text+0x1bc9): undefined reference to `clEnqueueNDRangeKernel'
gpu.c:(.text+0x1c16): undefined reference to `clEnqueueReadBuffer'
gpu.c:(.text+0x1c52): undefined reference to `clEnqueueReadBuffer'
gpu.c:(.text+0x1c8e): undefined reference to `clEnqueueReadBuffer'
gpu.c:(.text+0x1cca): undefined reference to `clEnqueueReadBuffer'
gpu.c:(.text+0x1ce2): undefined reference to `clFinish'
gpu.c:(.text+0x1d1c): undefined reference to `clSetKernelArg'
gpu.c:(.text+0x1daa): undefined reference to `clEnqueueNDRangeKernel'
gpu.c:(.text+0x1df0): undefined reference to `clEnqueueReadBuffer'
gpu.c:(.text+0x1e05): undefined reference to `clFinish'
collect2: error: ld returned 1 exit status
CMakeFiles/xmr-stak-amd.dir/build.make:333: recipe for target 'bin/xmr-stak-amd' failed
make[2]: *** [bin/xmr-stak-amd] Error 1
CMakeFiles/Makefile2:104: recipe for target 'CMakeFiles/xmr-stak-amd.dir/all' failed
make[1]: *** [CMakeFiles/xmr-stak-amd.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by psychocrypt** [comment]
Could you please post the cmake output of a clean repository! It looks like your opencl ist not found.

**Comment by EUViking** [comment]
From scratch with Master, which shows the initial problem, not reported here:
```
sysadm@gpu-miner-01:~/Miners/xmr-stak-amd/git$ rm -fr xmr-stak-amd
sysadm@gpu-miner-01:~/Miners/xmr-stak-amd/git$ git clone https://github.com/fireice-uk/xmr-stak-amd.git
Cloning into 'xmr-stak-amd'...
remote: Counting objects: 221, done.
remote: Total 221 (delta 0), reused 0 (delta 0), pack-reused 221
Receiving objects: 100% (221/221), 307.38 KiB | 0 bytes/s, done.
Resolving deltas: 100% (88/88), done.
sysadm@gpu-miner-01:~/Miners/xmr-stak-amd/git$ cd xmr-stak-amd/
sysadm@gpu-miner-01:~/Miners/xmr-stak-amd/git/xmr-stak-amd$ cmake .
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libssl.so;/usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sysadm/Miners/xmr-stak-amd/git/xmr-stak-amd
sysadm@gpu-miner-01:~/Miners/xmr-stak-amd/git/xmr-stak-amd$ make 
Scanning dependencies of target xmr-stak-amd
[  5%] Building C object CMakeFiles/xmr-stak-amd.dir/crypto/c_blake256.c.o
[ 11%] Building C object CMakeFiles/xmr-stak-amd.dir/crypto/c_groestl.c.o
[ 16%] Building C object CMakeFiles/xmr-stak-amd.dir/crypto/c_jh.c.o
[ 22%] Building C object CMakeFiles/xmr-stak-amd.dir/crypto/c_keccak.c.o
[ 27%] Building C object CMakeFiles/xmr-stak-amd.dir/crypto/c_skein.c.o
[ 33%] Building C object CMakeFiles/xmr-stak-amd.dir/crypto/soft_aes.c.o
[ 38%] Building CXX object CMakeFiles/xmr-stak-amd.dir/crypto/cryptonight_common.cpp.o
[ 44%] Building C object CMakeFiles/xmr-stak-amd.dir/amd_gpu/gpu.c.o
[ 50%] Building CXX object CMakeFiles/xmr-stak-amd.dir/cli-miner.cpp.o
[ 55%] Building CXX object CMakeFiles/xmr-stak-amd.dir/console.cpp.o
[ 61%] Building CXX object CMakeFiles/xmr-stak-amd.dir/executor.cpp.o
[ 66%] Building CXX object CMakeFiles/xmr-stak-amd.dir/httpd.cpp.o
[ 72%] Building CXX object CMakeFiles/xmr-stak-amd.dir/jconf.cpp.o
[ 77%] Building CXX object CMakeFiles/xmr-stak-amd.dir/jpsock.cpp.o
[ 83%] Building CXX object CMakeFiles/xmr-stak-amd.dir/minethd.cpp.o
[ 88%] Building CXX object CMakeFiles/xmr-stak-amd.dir/socket.cpp.o
[ 94%] Building CXX object CMakeFiles/xmr-stak-amd.dir/webdesign.cpp.o
[100%] Linking CXX executable bin/xmr-stak-amd
[100%] Built target xmr-stak-amd
sysadm@gpu-miner-01:~/Miners/xmr-stak-amd/git/xmr-stak-amd$ vi config.txt 
sysadm@gpu-miner-01:~/Miners/xmr-stak-amd/git/xmr-stak-amd$ bin/xmr-stak-amd 
[2017-05-16 00:19:20] : Compiling code and initializing GPUs. This will take a while...
[2017-05-16 00:19:20] : Device 0 work size 8 / 256.
-------------------------------------------------------------------
XMR-Stak-AMD mining software, AMD Version.
AMD mining code was written by wolf9466.
Brought to you by fireice_uk under GPLv3.

Configurable dev donation level is set to 1.0 %

You can use following keys to display reports:
'h' - hashrate
'r' - results
'c' - connection
-------------------------------------------------------------------
[2017-05-16 00:19:39] : Starting GPU thread, no affinity.
[2017-05-16 00:19:39] : Connecting to pool mine.moneropool.com:443 ...
[2017-05-16 00:19:40] : Connected. Logging in...
[2017-05-16 00:19:40] : Difficulty changed. Now: 25000.
[2017-05-16 00:19:40] : New block detected.
[2017-05-16 00:19:48] : New block detected.
Illegal instruction (core dumped)
```
Not sure where that core dump ends up though...

**Comment by EUViking** [comment]
From syslog:
```
May 16 00:20:45 gpu-miner-01 kernel: [93027.472331] traps: xmr-stak-amd[4274] trap invalid opcode ip:55887f0e7088 sp:7fe43994f980 error:0
May 16 00:20:45 gpu-miner-01 kernel: [93027.472343]  in xmr-stak-amd[55887f0cc000+45000]
```

**Comment by EUViking** [comment]
As the setting for HashReport is 60 seconds and this crash comes around the same time, something related to collecting/calculating the hash-rate may be involved here.

**Comment by EUViking** [comment]
OK, figured out my original problem:
```
Illegal instruction (core dumped)
This typically means you are trying to run it on a CPU that does not have AES. This only happens on older version of miner, new version gives better error message (but still wont' work since your CPU doesn't support the required instructions).
```
[xmr-stak-cpu Illegal instruction](https://github.com/fireice-uk/xmr-stak-cpu#common-issues)
Obviously the same applies for the GPU-Miner
As the root-cause of my problem is more with the HW I am trying to run on, than with the SW, this issue may be regarded Solved. 
@psychocrypt's fix seems to have fixed what it was supposed to fix, according to my test.
